-- ============================================================
-- Jan Suvidha Kendra — Supabase setup for the lead form
-- Run this in Supabase Dashboard > SQL Editor > New query > Run
-- ============================================================

-- 1) Leads table
create table if not exists public.leads (
  id          bigint generated by default as identity primary key,
  name        text not null,
  phone       text not null,
  city        text,
  experience  text,
  source      text default 'landing-page',
  created_at  timestamptz default now()
);

-- 2) Enable Row Level Security
alter table public.leads enable row level security;

-- 3) Allow the public (anon) key to INSERT only — visitors can submit,
--    but NOBODY can read leads with the anon key. You read them in the
--    Supabase Table Editor (which uses your service role).
drop policy if exists "anon can insert leads" on public.leads;
create policy "anon can insert leads"
  on public.leads
  for insert
  to anon
  with check (true);

-- (No SELECT/UPDATE/DELETE policy for anon = those are blocked. Good.)

-- ============================================================
-- AFTER RUNNING:
-- Project Settings > API  -> copy:
--   • Project URL   -> CONFIG.SUPABASE_URL   in index.html
--   • anon public key -> CONFIG.SUPABASE_ANON in index.html
-- View / export leads:  Table Editor > leads  (filter, sort, Export CSV)
-- ============================================================
